### PR TITLE
fix tree selectionInactiveBackground

### PR DESCRIPTION
**Pull request by nklbdev**
I noticed that when using this theme, the current selection in the project tree becomes invisible when SolutionExplorer is not in focus. This is somewhat disorienting when the "Always Select Open File" option is enabled, and I'm switching between tabs, the highlight of the selected file in SolutionExplorer remains invisible.

PS:
Your color scheme is just amazing! I used to use the Monokai scheme and its derivatives everywhere, but they required additional fitting. Your scheme turned out to be harmonious and complete, and suitable for daily productive work!

### CODE REVIEW

**Comment by elliotwaite** [comment]
Hi, thanks for the PR! And I'm glad you've been enjoying the theme.

I hadn't been using the "Always Select Opened File" option, so I hadn't noticed this issue before. Thanks for pointing it out.

I tested out changing `selectionInactiveBackground` to both `grey8` and `grey9`, and I kind of liked the `grey8` version more since there was still a slight difference between the active version (`"selectionBackground": "grey9"`) which helped me distinguish between when that panel was active or not, and I also kind of liked the selection being a bit more subtle when the window wasn't active. What are your thoughts on going with `grey8` vs `grey9`, do you like the `grey9` version better?

**Comment by nklbdev** [comment]
Hi, @elliotwaite ! I'm ok with any value that differs from the background! Use any you like, and I'll reload the theme 🥳

**Comment by elliotwaite** [comment]
Okay, sounds good. I merged the PR, and I'll change it to use `grey8` before releasing it. I'll submit the updated version for review today and it should be approved and available for download as a plugin update in the next few days.

**Comment by nklbdev** [comment]
Thank you! Bye!

**Pull request merged**
